WITH agent_daily_sale AS (
select A.AGENT_CODE,AGENT_NAME,ORD_DATE,SUM(O.ORD_AMOUNT) SUM_ORD_AMT 
from ORDERS_STG O 
JOIN AGENTS_STG A ON A.AGENT_CODE = O.AGENT_CODE
 GROUP BY A.AGENT_CODE,AGENT_NAME,O.ORD_DATE
 ORDER BY A.AGENT_CODE,O.ORD_DATE
 )
 SELECT * FROM agent_daily_sale
